name: Generate blog

on: [push]
jobs:
  generate:
    name: MD to HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: BaileyJM02/markdown-to-pdf@v1
        with:
          input_dir: blog-pages
          output_dir: blog
          extend_default_theme: false
          template: blog-template.html
      - uses: EndBug/add-and-commit@v9
        with:
          add: blog/*.html
          message: 'BOT: Automatically converting Markdown to HTML'

