name: Generate blog

on: [push]
jobs:
  generate:
    name: MD to HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16
      - run: npm install -g markdown-folder-to-html
      - run: |
          markdown-folder-to-html docs
          mv -f _docs blog
      - uses: EndBug/add-and-commit@v9
        with:
          add: blog/*
          message: 'BOT: Automatically converting Markdown to HTML'

